language: cpp

compiler:
  - clang++

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-test-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ctest --output-on-failure
