language: cpp

compiler:
  - clang++

before_install:
  - sudo apt-get update
  - sudo apt-get install libboost-test-dev

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCOVERALLS=true
  - make
  - make coveralls

after_success:
  - ./coveralls-upload
